from PIL import Image
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import numpy
import math

img = Image.open('103_5.tif', 'r')
pix_vals = list(img.getdata())
new_pix1 = list()
new_pix2 = list()
new_pix3 = list()
new_pix4 = list()
new_pix5 = list()
for i in pix_vals:
    new_pix1.append(1*math.log(1+i))
    new_pix2.append(5*math.log(1+i))
    new_pix3.append(10*math.log(1+i))
    new_pix4.append(0.1*math.log(1 + i))
    new_pix5.append(0.5*math.log(1 + i))
plt.imsave('logtransform1.png', numpy.array(new_pix1).reshape(374, 388), cmap=cm.gray)
img1 = Image.open('logtransform1.png', 'r')
plt.imsave('logtransform2.png', numpy.array(new_pix2).reshape(374, 388), cmap=cm.gray)
img2 = Image.open('logtransform2.png', 'r')
plt.imsave('logtransform3.png', numpy.array(new_pix3).reshape(374, 388), cmap=cm.gray)
img3 = Image.open('logtransform3.png', 'r')
plt.imsave('logtransform4.png', numpy.array(new_pix4).reshape(374, 388), cmap=cm.gray)
img4 = Image.open('logtransform4.png', 'r')
plt.imsave('logtransform5.png', numpy.array(new_pix5).reshape(374, 388), cmap=cm.gray)
img5 = Image.open('logtransform5.png', 'r')
fig, ((ax0, ax1), (ax2, ax3), (ax4, ax5)) = plt.subplots(3, 2)
ax0.imshow(img, cmap='gray')
ax0.axis('off')
ax0.set_title('Original Image')
ax1.imshow(img1, cmap='gray')
ax1.axis('off')
ax1.set_title('C = 1')
ax2.imshow(img2, cmap='gray')
ax2.axis('off')
ax2.set_title('C = 5')
ax3.imshow(img3, cmap='gray')
ax3.axis('off')
ax3.set_title('C = 10')
ax4.imshow(img4, cmap='gray')
ax4.axis('off')
ax4.set_title('C = 0.1')
ax5.imshow(img5, cmap='gray')
ax5.axis('off')
ax5.set_title('C = 0.5')
plt.show()
